apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Srinivas-Ravindranath/log-cruncher-argo.git # Replace with your repo
    targetRevision: HEAD
    path: sample-apps/logger
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m