apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: elasticsearch-storage
  hostPath:
    path: /mnt/data/elasticsearch
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Delete
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker-node-1
                - worker-node-2