apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: elasticsearch-storage    # ← lower-case
  hostPath:
    path: /mnt/data/elasticsearch
    type: DirectoryOrCreate                 # ← auto-create the dir
  persistentVolumeReclaimPolicy: Delete