apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: logging
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup:   1000

      initContainers:
      - name: fix-perms
        image: busybox:latest
        command:
          - sh
          - -c
          - |
            chown -R 1000:1000 /usr/share/elasticsearch/data
        volumeMounts:
          - name: data
            mountPath: /usr/share/elasticsearch/data

      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        ports:
          - containerPort: 9200
            name: rest
          - containerPort: 9300
            name: inter-node
        env:
          - name: cluster.name
            value: log-cruncher-cluster
          - name: discovery.type
            value: single-node
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
          - name: xpack.security.enabled
            value: "false"
        volumeMounts:
          - name: data
            mountPath: /usr/share/elasticsearch/data

  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: elasticsearch-storage
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 15Gi