apiVersion: v1
kind: Service
metadata:
  name: production-app
  namespace: sample-apps
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app: production-app
  ports:
  - port: 80
    targetPort: 5000
    name: http
  type: ClusterIP