## monitoring/node-exporter/node-exporter.yaml
#apiVersion: apps/v1
#kind: DaemonSet
#metadata:
#  name: node-exporter
#  namespace: monitoring
#  labels:
#    app: node-exporter
#  annotations:
#    argocd.argoproj.io/sync-wave: "2"  # Deploy after namespace
#spec:
#  selector:
#    matchLabels:
#      app: node-exporter
#  template:
#    metadata:
#      labels:
#        app: node-exporter
#    spec:
#      hostNetwork: true
#      hostPID: true
#      tolerations:
#      - operator: Exists
#        effect: NoSchedule
#      containers:
#      - name: node-exporter
#        image: prom/node-exporter:v1.7.0
#        args:
#        - '--path.procfs=/host/proc'
#        - '--path.sysfs=/host/sys'
#        - '--path.rootfs=/host/root'
#        - '--collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+)($|/)'
#        - '--collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)
#        ports:
#        - containerPort: 9100
#          name: metrics
#          protocol: TCP
#        resources:
#          limits:
#            cpu: 200m
#            memory: 200Mi
#          requests:
#            cpu: 100m
#            memory: 100Mi
#        volumeMounts:
#        - name: proc
#          mountPath: /host/proc
#          readOnly: true
#        - name: sys
#          mountPath: /host/sys
#          readOnly: true
#        - name: root
#          mountPath: /host/root
#          mountPropagation: HostToContainer
#          readOnly: true
#      volumes:
#      - name: proc
#        hostPath:
#          path: /proc
#      - name: sys
#        hostPath:
#          path: /sys
#      - name: root
#        hostPath:
#          path: /
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: node-exporter
#  namespace: monitoring
#  labels:
#    app: node-exporter
#  annotations:
#    argocd.argoproj.io/sync-wave: "2"
#spec:
#  type: ClusterIP
#  ports:
#  - port: 9100
#    targetPort: 9100
#    name: metrics
#  selector:
#    app: node-exporter